create table ponto_interesse (
                                 id integer generated by default as identity,
                                 coordenadax integer,
                                 coordenaday integer,
                                 descricao varchar(255),
                                 horario_abertura TIME,
                                 horario_fechamento TIME,
                                 primary key (id)
);

alter table ponto_interesse add constraint UNQ_PI_X_Y UNIQUE (coordenadax, coordenaday);